"""Skill taxonomy: canonical name -> alias spellings found in real JDs.

Used on BOTH sides of the fit score: the same matcher runs over content.yaml
(my profile) and over each job description, so a skill only ever counts if the
exact term (or a listed alias) literally appears in both texts. Extend freely —
adding an alias can only make matching more accurate, never invent a skill.
"""

TAXONOMY = {
    # Languages
    "javascript": ["javascript", "js"],
    "typescript": ["typescript", "ts"],
    "python": ["python"],
    "java": ["java"],
    "c#": ["c#", "csharp", ".net", "dotnet"],
    "c++": ["c++", "cpp"],
    "go": ["golang", "go developer", "go engineer", "(go)"],
    "ruby": ["ruby", "rails", "ruby on rails"],
    "php": ["php", "laravel"],
    "kotlin": ["kotlin"],
    "swift": ["swift"],
    "rust": ["rust"],
    "scala": ["scala"],
    "sql": ["sql"],
    "html": ["html", "html5"],
    "css": ["css", "css3", "scss", "sass"],
    # Frontend
    "react": ["react", "react.js", "reactjs"],
    "next.js": ["next.js", "nextjs", "next js"],
    "vue": ["vue", "vue.js", "vuejs", "nuxt"],
    "angular": ["angular", "angularjs"],
    "tailwind": ["tailwind", "tailwindcss"],
    "redux": ["redux"],
    "responsive ui": ["responsive", "mobile-first"],
    "shadcn": ["shadcn"],
    # Backend / APIs
    "node.js": ["node.js", "nodejs", "node js", "node"],
    "nestjs": ["nestjs", "nest.js"],
    "express": ["express", "express.js"],
    "flask": ["flask"],
    "django": ["django"],
    "fastapi": ["fastapi"],
    "spring": ["spring", "spring boot"],
    "rest api": ["rest api", "rest apis", "restful", "rest services"],
    "graphql": ["graphql"],
    "grpc": ["grpc"],
    "websockets": ["websocket", "websockets"],
    "microservices": ["microservice", "microservices"],
    "oauth": ["oauth", "oauth2", "oauth 2"],
    "jwt": ["jwt", "json web token"],
    "webhooks": ["webhook", "webhooks"],
    # AI
    "llm": ["llm", "llms", "large language model", "genai", "generative ai"],
    "rag": ["rag", "retrieval-augmented", "retrieval augmented"],
    "embeddings": ["embedding", "embeddings"],
    "vector search": ["vector search", "vector database", "pgvector", "pinecone",
                      "weaviate", "qdrant"],
    "openai api": ["openai", "gpt-4", "gpt4", "chatgpt api"],
    "prompt engineering": ["prompt engineering", "prompting"],
    "machine learning": ["machine learning", "ml engineer", "ml models"],
    # Data / storage
    "postgresql": ["postgres", "postgresql"],
    "mysql": ["mysql", "mariadb"],
    "mongodb": ["mongodb", "mongo"],
    "redis": ["redis"],
    "elasticsearch": ["elasticsearch", "opensearch"],
    "supabase": ["supabase"],
    "firebase": ["firebase"],
    "kafka": ["kafka"],
    "rabbitmq": ["rabbitmq"],
    # Cloud / infra
    "aws": ["aws", "amazon web services", "ec2", "lambda", "s3"],
    "gcp": ["gcp", "google cloud"],
    "azure": ["azure"],
    "docker": ["docker", "containers", "containerized"],
    "kubernetes": ["kubernetes", "k8s"],
    "terraform": ["terraform"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration", "continuous delivery",
              "github actions", "gitlab ci", "jenkins"],
    "linux": ["linux", "unix"],
    "serverless": ["serverless"],
    # Integrations / payments
    "stripe": ["stripe"],
    "paypal": ["paypal"],
    "payments": ["payment", "payments", "payment processing", "razorpay"],
    "google apis": ["google apis", "google api"],
    "zapier": ["zapier"],
    "make": ["make.com", "integromat"],
    "xano": ["xano"],
    "bubble.io": ["bubble.io", "bubble"],
    "wordpress": ["wordpress"],
    "third-party integrations": ["third-party integration", "third party integration",
                                 "api integration", "api integrations", "integrations"],
    "postman": ["postman"],
    "analytics": ["google analytics", "meta pixel", "mixpanel", "segment"],
    # Practices / tooling
    "git": ["git", "github", "gitlab", "version control"],
    "testing": ["unit test", "unit testing", "integration test", "jest",
                "pytest", "cypress", "playwright", "tdd", "test-driven"],
    "agile": ["agile", "scrum", "kanban", "sprint"],
    "code review": ["code review", "code reviews", "pull request"],
    "security": ["security best practices", "owasp", "application security"],
    "rls": ["rls", "row level security", "row-level security"],
    "system design": ["system design", "architecture", "architectural"],
    "monitoring": ["monitoring", "observability", "datadog", "grafana", "sentry"],
    # Soft/delivery (only ones content.yaml genuinely claims)
    "team leadership": ["team lead", "leadership", "leading a team", "mentoring",
                        "mentor", "lead a team"],
    "stakeholder management": ["stakeholder", "stakeholders"],
    "client communication": ["client-facing", "client facing", "customer-facing",
                             "client communication"],
    "product scoping": ["scoping", "requirements gathering", "technical planning",
                        "sow", "statement of work", "estimates", "estimation",
                        "discovery calls", "discovery phase", "pre-sales"],
    "solution architecture": ["solution architect", "solutions architect",
                              "solution architecture", "solution design"],
    "product ownership": ["product owner", "product ownership"],
    "qa ownership": ["qa process", "quality assurance process"],
    "english": ["english"],
}
