"""Centralized file-path resolution for ApplyBro's user data.

Single source of truth for where config/resume/data files live. Today
everything resolves relative to the current working directory (ApplyBro is
run from its project root) — that assumption lives here and ONLY here, so a
future packaging step (e.g. installing to ~/.applybro/) is a one-line change
here instead of an edit across the whole project.

Layout: the CONFIG SURFACE (config/profile + Google credential) stays at the
project root where the setup wizard tells users to put it; the RESUME SYSTEM
(layout + content + build) lives in resume/; all RUNTIME STATE the app
generates lives in data/ (gitignored wholesale).

Workspace-internal filenames (job.md, content.tailored.yaml, answers.yaml,
...) are NOT centralized here — they're relative to a given workspace dir
passed as an argument, not root-level user data.
"""
from __future__ import annotations

# --- config surface (project root — users edit/place these by hand) --------
CONFIG_YAML = "config.yaml"
CONFIG_EXAMPLE_YAML = "config.example.yaml"
PROFILE_YAML = "profile.yaml"
PROFILE_EXAMPLE_YAML = "profile.example.yaml"
CREDENTIALS_JSON = "credentials.json"
TOKEN_JSON = "token.json"

# --- resume system (resume/ — layout/content separation per CLAUDE.md) -----
RESUME_DIR = "resume"
CONTENT_YAML = "resume/content.yaml"
TEMPLATE_TYP = "resume/template.typ"
BUILD_SH = "resume/build.sh"
RESUME_PDF = "resume/resume.pdf"
MASTER_RESUME_DIR = "resume/Master Resume"

# --- runtime state (data/ — generated by the app, gitignored wholesale) ----
DATA_DIR = "data"
UI_STATE_JSON = "data/ui_state.json"
APPLICATIONS_DIR = "data/applications"
QUEUE_JSON = "data/applications/queue.json"
QUEUE_META_JSON = "data/applications/queue.meta.json"
# The company list — the discovery SOURCE now lives locally, not in a Google
# Sheet (decided 2026-07-12). See backend/app/companies.py.
COMPANIES_JSON = "data/companies.json"
# The signed-in Supabase session (tokens) — inside gitignored data/.
SESSION_JSON = "data/session.json"

# Legacy CSV pipeline (the public/no-OAuth CLI mode) — also runtime state.
JOB_LOG_CSV = "data/job_log.csv"
JOB_SCORES_CSV = "data/job_scores.csv"
